---
name: 'Test AWS OIDC'
'on':
  workflow_dispatch: null
permissions:
  id-token: 'write'
  contents: 'read'
jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Configure AWS credentials'
        uses: 'aws-actions/configure-aws-credentials@v4'
        with:
          role-to-assume: 'arn:aws:iam::651629222199:role/github-access-role'
          aws-region: 'eu-central-1'
      - name: 'Test AWS identity'
        run: 'aws sts get-caller-identity'
